add_newline = true
prompt_order = [
    "directory",
    "git_branch",
    "git_commit",
    "git_status",
    "aws",
    "kubernetes",
    "line_break",
    "character"
]

[kubernetes]
disabled = false

[character]
symbol = "➜"
error_symbol = "✗"
use_symbol_for_status = true

[aws]
symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
symbol = " "

[docker]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "
